openapi: '3.0.2'

info:
  title: Plataforma Caracas - Eventos
  description: App para cadastro de eventos e suas dependencias
  version: '0.0.1'

servers:
- url: https://definir_url_base
  description: Servidor de Desenvolvimento da API

tags:
- name: "Tipo"
- name: "Categoria"
- name: "Atividade"
- name: "Evento"

paths:
  /evento/v1/tipo:
   post:
    tags:
      - "Tipo"
    description: Cadastra um novo tipo de evento
    operationId: postTipoEvento
    parameters:
      - name: nomeTipo
        in: query
        description: Nome do tipo de evento
        required: true
        schema:
          type: string
    responses:
      '201': 
        description: Novo `tipo` de evento criado com sucesso
      '401': 
        description: Unauthorized
      '403': 
        description: Forbiden
      '500': 
        description: Internal Server Error

  /evento/v1/categoria:
   post:
    tags:
      - "Categoria"
    description: Cadastra uma nova categoria de evento
    operationId: postCategoriaEvento
    requestBody:
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Categoria'
    responses:
      '201': 
        description: Nova `categoria` de evento criada com sucesso
      '401': 
        description: Unauthorized
      '403': 
        description: Forbiden
      '500': 
        description: Internal Server Error

  /evento/v1/atividade:
   post:
    tags:
      - "Atividade"
    description: Cadastra uma nova atividade de evento
    operationId: postAtividadeEvento
    requestBody:
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Atividade'
    responses:
      '201': 
        description: Nova `atividade` criada com sucesso
      '401': 
        description: Unauthorized
      '403': 
        description: Forbiden
      '500': 
        description: Internal Server Error


components:
  schemas:

    Categoria:
      type: object
      properties:
        nomeCategoria:
          type: string
          description: Nome da categoria do evento
          example: Congresso
        descricaoCategoria:
          type: string
          description: Breve descrição da categoria
          example: Evento para apresentação de portifolio
        statusCategoria:
          type: boolean
          description: Status da categoria, se esta ativa ou não
          example: true
    Atividade:
      type: object
      properties:
        nomeAtividade:
          type: string
          description: Nome da atividade em um evento
          example: Workshop
        statusAtividade:
          type: boolean
          description: Status da atividade, se esta ativa ou não
          example: true





