openapi: '3.0.2'

info:
  title: Plataforma Caracas - Eventos
  description: App para gestão de eventos e suas dependencias,tais quais atividade, categoria e tipo
  version: '0.0.1'

servers:
- url: https://definir_url_base
  description: Servidor de Desenvolvimento da API

tags:
- name: "Tipo"
- name: "Categoria"
- name: "Atividade"
- name: "Evento"

paths:
  /evento/v1/tipo:
   post:
    tags:
      - "Tipo"
    description: Cadastra um novo tipo de evento
    operationId: postTipoEvento
    requestBody:
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Tipo'
    responses:
      '201': 
        description: Novo `tipo` de evento criado com sucesso
      '401': 
        description: Unauthorized
      '403': 
        description: Forbiden
      '500': 
        description: Internal Server Error

  /evento/v1/categoria:
   post:
    tags:
      - "Categoria"
    description: Cadastra uma nova categoria de evento
    operationId: postCategoriaEvento
    requestBody:
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Categoria'
    responses:
      '201': 
        description: Nova `categoria` de evento criada com sucesso
      '401': 
        description: Unauthorized
      '403': 
        description: Forbiden
      '500': 
        description: Internal Server Error

  /evento/v1/atividade:
   post:
    tags:
      - "Atividade"
    description: Cadastra uma nova atividade de evento
    operationId: postAtividadeEvento
    requestBody:
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Atividade'
    responses:
      '201': 
        description: Nova `atividade` criada com sucesso
      '401': 
        description: Unauthorized
      '403': 
        description: Forbiden
      '500': 
        description: Internal Server Error

  /evento/v1/evento:
   post:
    tags:
      - "Evento"
    description: Cadastra um novo Evento
    operationId: postEvento
    requestBody:
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Evento'
    responses:
      '201': 
        description: Novo `evento` criado com sucesso
      '401': 
        description: Unauthorized
      '403': 
        description: Forbiden
      '500': 
        description: Internal Server Error



components:
  schemas:

    Tipo:
      type: object
      required:
          - nomeTipo
          - descricaoTipo
          - statusTipo
      properties:
        nomeTipo:
          type: string
          description: Nome do Tipo do evento
          example: Acadêmico
        descricaoTipo:
          type: string
          description: Breve descrição do Tipo
          example: Evento de nicho acadêmico
        statusTipo:
          type: boolean
          description: Status do Tipo, se esta ativo ou não
          example: true

    Categoria:
      type: object
      required:
          - nomeCategoria
          - descricaoCategoria
          - statusCategoria
      properties:
        nomeCategoria:
          type: string
          description: Nome da categoria do evento
          example: Congresso
        descricaoCategoria:
          type: string
          description: Breve descrição da categoria
          example: Evento para apresentação de portifolio
        statusCategoria:
          type: boolean
          description: Status da categoria, se esta ativa ou não
          example: true

    Atividade:
      type: object
      required:
          - nomeAtividade
          - statusAtividade
      properties:
        nomeAtividade:
          type: string
          description: Nome da atividade em um evento
          example: Workshop
        statusAtividade:
          type: boolean
          description: Status da atividade, se esta ativa ou não
          example: true

    Evento:
      type: object
      properties:
        nomeEvento:
          type: string
          description: Nome do Evento
          example: SIMGETEC
        descricaoEvento:
          type: string
          description: Breve descrição do Evento
          example: Simposio de Gestão e Tecnologia da FATEC Carapicuiba
        dataInicio:
          type: string
          format: date
          description: Data que inicia o evento
          example: '2021-12-07'
        dataFim:
          type: string
          format: date          
          description: Data que encerra o evento
          example: '2021-12-10'
        tipoEvento:
          type: string
          description: Tipo do evento
          example: Acadêmico
        categoriaEvento:
          type: string
          description: Categoria do evento
          example: Simpósio
        atividadesEvento:
          type: array
          description: Atividades do evento
          items:
            $ref: '#/components/schemas/AtividadeEvento'
        statusEvento:
          type: boolean
          description: Status do evento, se esta ativo ou não
          example: true
          
    AtividadeEvento:
      allOf:
        - $ref: '#/components/schemas/Atividade'
      type: object
      required:
          - quantidadeVagas
      properties:
        quantidadeVagas:
          type: integer
          description: Limites de vagas por atividade
          example: 30





